<table class="bean_details">
    <thead>
        <tr>
            <th>Property</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>boardHeight</td>
            <td>${beanData.boardHeight}</td>
        </tr>
        <tr>
            <td>boardWidth</td>
            <td>${beanData.boardWidth}</td>
        </tr>
        <tr>
            <td>cellQuantity<br />(calculated value)</td>
            <td>${beanData.cellQuantity}</td>
        </tr>
        <tr>
            <td>iconEmpty</td>
            <td>${beanData.iconEmpty}</td>
        </tr>
        <tr>
            <td>iconPlayer1</td>
            <td>${beanData.iconPlayer1}</td>
        </tr>
        <tr>
            <td>iconPlayer2</td>
            <td>${beanData.iconPlayer2}</td>
        </tr>
        <tr>
            <td>board</td>
            <td>${beanData.board}</td>
        </tr>
        <tr>
            <td>player1Turn</td>
            <td>${beanData.player1Turn}</td>
        </tr>
        <tr>
            <td>gameOver</td>
            <td>${beanData.gameOver}</td>
        </tr>
        <tr>
            <td>turnString</td>
            <td>${beanData.turnString}</td>
        </tr>
        <tr>
            <td>player1Score</td>
            <td>${beanData.player1Score}</td>
        </tr>
        <tr>
            <td>player2Score</td>
            <td>${beanData.player2Score}</td>
        </tr>
        <tr>
            <td>draws</td>
            <td>${beanData.draws}</td>
        </tr>
    </tbody>
</table>